version: "3.8"

services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-llm
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ollama-backend
    restart: unless-stopped
    ports:
      - "5114:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Ollama__BaseUrl=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - backend_logs:/app/logs

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ollama-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  ollama_data:
    driver: local
  backend_logs:
    driver: local

networks:
  app-network:
    driver: bridge
